REDUCE_SIZE_SCREEN = 1.8

"""         SCREEN MANAGEMENT         """
WIDTH, HEIGHT = 1080 // REDUCE_SIZE_SCREEN, 1920 // REDUCE_SIZE_SCREEN
BACKGROUND_COLOR = (5, 5, 5)

"""         TIME MANAGEMENT         """
FPS = 60
TIME_VIDEO = 56 #seconds
TIME_END_VIDEO = 6 #seconds

"""         CIRCLE MANAGEMENT         """
CIRCLE_BASE_RADIUS = 400 // REDUCE_SIZE_SCREEN
CIRCLE_MIN_SIZE = 300 // REDUCE_SIZE_SCREEN
NUMBER_CIRCLES = 200
HOLE_SIZE_DEGRE = 50

"""         BALL MANAGEMENT         """
GRAVITY = 0.55 / REDUCE_SIZE_SCREEN
BALL_RADIUS = 50 // REDUCE_SIZE_SCREEN
POS_SPAWN_BALL_Y = 1000 // REDUCE_SIZE_SCREEN
POS_SPAWN_BALL_X_RANGE = 90 // REDUCE_SIZE_SCREEN
BALL_MIN_SPEED = 20 // REDUCE_SIZE_SCREEN

"""         PARTICLES MANAGEMENT         """
NUMBER_PARTICLES = 200

COLOR_LIST = [(0, 210, 0), (255, 0, 0), (100, 87, 255), (255, 255, 0), (255, 0, 255), (0, 255, 255)]

"""         QUESTION AND ANSWERS MANAGEMENT         """
import pygame
pygame.init()
QUESTION = "ça va ?"

# FONT TEXT
FONT = pygame.font.SysFont(None, int(83 // REDUCE_SIZE_SCREEN))
LITTLE_FONT = pygame.font.SysFont(None, int(60 // REDUCE_SIZE_SCREEN))
WINNER_FONT = pygame.font.SysFont(None, int(120 // REDUCE_SIZE_SCREEN))
TEXT_QUESTION = FONT.render(QUESTION, True, (0, 0, 0))
TEXT_QUESTION_POS = [WIDTH / 2 - TEXT_QUESTION.get_width() / 2, 250 // REDUCE_SIZE_SCREEN]
TEXT_WINNER_POS = [WIDTH / 2, 1500 // REDUCE_SIZE_SCREEN]
WINNER_SIZE = [500 // REDUCE_SIZE_SCREEN, 350 // REDUCE_SIZE_SCREEN]
TEXT_TIMER_POS_Y = 1500 // REDUCE_SIZE_SCREEN

RESPONSES_NUMBER = 2 #max 6
RESPONSE_1 = "Yes"
RESPONSE_2 = "No"
RESPONSE_3 = "Maybe"
RESPONSE_4 = "42"
RESPONSE_5 = "UwU"
RESPONSE_6 = "(ca)²"
RESPONSES_LIST = [RESPONSE_1, RESPONSE_2, RESPONSE_3, RESPONSE_4, RESPONSE_5, RESPONSE_6]

"""         ZONE ANSWERS MANAGEMENT         """
#HEIGHT - ZONE_POSITION_Y = position on screen
ZONE_POSITION_Y = 400 / REDUCE_SIZE_SCREEN
ZONE_WIDTH = 50 * max(len(RESPONSES_LIST[i]) for i in range(RESPONSES_NUMBER)) / REDUCE_SIZE_SCREEN
ZONE_HEIGHT = 180 / REDUCE_SIZE_SCREEN