REDUCE_SIZE_SCREEN = 2.3

"""         SCREEN MANAGEMENT         """
WIDTH, HEIGHT = 1080 // REDUCE_SIZE_SCREEN, 2400 // REDUCE_SIZE_SCREEN
BACKGROUND_COLOR = (5, 5, 5)

"""         TIME MANAGEMENT         """
FPS = 62
TIME_VIDEO = 57 #seconds
TIME_END_VIDEO = 5 #seconds

"""         CIRCLE MANAGEMENT         """
CIRCLE_BASE_RADIUS = 470 // REDUCE_SIZE_SCREEN

"""         BALL MANAGEMENT         """
GRAVITY = 0.7 / REDUCE_SIZE_SCREEN
BALL_RADIUS = 20 // REDUCE_SIZE_SCREEN
POS_SPAWN_BALL_Y = 1000 // REDUCE_SIZE_SCREEN
POS_SPAWN_BALL_X_RANGE = 90 // REDUCE_SIZE_SCREEN
MIN_SPEED = 26 // REDUCE_SIZE_SCREEN

"""         ZONE ANSWERS MANAGEMENT         """
#HEIGHT - ZONE_POSITION_Y = position on screen
ZONE_POSITION_Y = 600 // REDUCE_SIZE_SCREEN

COLOR_LIST = [(0, 255, 0), (255, 0, 0), (100, 87, 255), (255, 255, 0), (255, 0, 255), (0, 255, 255)]

"""         QUESTION AND ANSWERS MANAGEMENT         """
import pygame
pygame.init()
QUESTION = "Is your bro gay ?"

# FONT TEXT
FONT = pygame.font.SysFont(None, 36)
TEXT_QUESTION = FONT.render(QUESTION, True, (255, 255, 255))
TEXT_QUESTION_POSITION_Y = 250 // REDUCE_SIZE_SCREEN
TEXT_QUESTION_POS = (WIDTH / 2 - TEXT_QUESTION.get_width() / 2, TEXT_QUESTION_POSITION_Y)

RESPONSES_NUMBER = 2 #max 6
RESPONSE_1 = "Yes"
RESPONSE_2 = "No"
RESPONSE_3 = "Maybe"
RESPONSE_4 = "42"
RESPONSE_5 = "UwU"
RESPONSE_6 = "(ca)²"
RESPONSES_LIST = [RESPONSE_1, RESPONSE_2, RESPONSE_3, RESPONSE_4, RESPONSE_5, RESPONSE_6]

from zone import ZoneDetector
zone_width = WIDTH // RESPONSES_NUMBER
zone_height = ZONE_POSITION_Y / 2
ZONES = []
for i in range(RESPONSES_NUMBER):
    ZONES.append(ZoneDetector(0 + i * zone_width, zone_height, zone_width, COLOR_LIST[i], RESPONSES_LIST[i]))